# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    target-branch: "master"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Allow up to 10 open pull requests for maven dependencies
    open-pull-requests-limit: 20
    
  # Maintain dependencies for Maven (3.0.0 milestones)
  - package-ecosystem: "maven"
    target-branch: "spring6"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Allow up to 10 open pull requests for maven dependencies
    open-pull-requests-limit: 20


