github:
  description: "Apache Causeway™ software is a framework for rapidly developing domain-driven apps in Java. Write your business logic in entities, domain services or view models, and the framework dynamically generates a representation of that domain model as a webapp or as a RESTful API. For prototyping or production. "
  homepage: https://causeway.apache.org/
  labels:
    - java
    - web-framework
    - domain-driven-design
    - ddd
    - rapid-application-development
    - rad
    - naked-objects
    - restful-objects
